### PR TITLE
Just added a few extra configuration options

### PR DESCRIPTION
**Pull request by kardolus**
First of all...

This is super incredible!! So good. How did you come up with this? Reminds me so much of what we used back at Pivotal. Check this for example: https://concourse-summary-crystal.cfapps.io/host/buildpacks.ci.cf-app.com

Feel free to decline/close my PR. Just needed this for our org but understand if you don't see a use for it. 

Ah you prolly also want to squash my commits in case you do want to take it.

### CODE REVIEW

**Comment by srbry** [comment]
Hi @kardolus thanks for the PR and the feedback. I have used both concourse summary and the new concourse dashboards to great effect in the past and it was definitely part of the inspiration for this.

You may have already seen it but we also wrote a blog about our creation of this tool and the behaviours we hope it will help to drive: https://cloudnative.ly/giving-circleci-a-focus-on-continuous-deployment-36fe835c97be.

As far as the PR goes I really like the features, I have actually been thinking about putting some more work into filtering branches at some point but this is definitely the simplest option, given how much of the community use CircleCI we think we might also need to worry about filtering multiple branches, possibly by regex and possibly even different per repo but we definitely don't want to block a useful feature based on that.

Hopefully you don't mind but I refactored your changes out a bit to make it easier to test and this is now in master https://github.com/armakuni/circleci-workflow-dashboard/commit/e5a1b272374bb5e9aebd7b7111d5df62bf4803f0.

Let me know if you are happy for me to close this PR

**Comment by srbry** [comment]
Oh and the new features will also be available using the latest docker image or the latest tagged version: https://hub.docker.com/layers/armakuni/circleci-workflow-dashboard/1.0.72/images/sha256-e5f0e2524ba7d8b50736ae5443e67551733686f1e3549c7c5e07ec28f7c46d3f?context=explore

**Comment by kardolus** [comment]
Thanks dude, yeah, you can totally close the PR. Oh I do have a question. Do you think it's a good idea to put most of the configuration in an `application.yml`? Was thinking about making like a configurator. In that way it's also easy to define a list of branches (per repo) you'd like to see.

**Comment by srbry** [comment]
A configuration file would be cool, I think we would need to keep anything secret out of it by default to keep it easy to consume so the `CIRCLECI_TOKEN` would still be an env var. I also want to make sure that keep it super easy for someone to just start up the Docker file. Maybe that's just an example and a script to create a temporary file and mount it into the container.

**Pull request closed without merging**
